-- ==========================================
-- Sephora Beauty E-Commerce Website
-- Customer.sql
-- ==========================================

-- Create Customer Table
CREATE TABLE Customer (
    Customer_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    First_Name VARCHAR2(50) NOT NULL,
    Last_Name VARCHAR2(50) NOT NULL,
    Gender VARCHAR2(10),
    Email VARCHAR2(100) UNIQUE,
    Phone VARCHAR2(15),
    Password VARCHAR2(255),
    Address VARCHAR2(255),
    City VARCHAR2(50),
    State VARCHAR2(50),
    Pincode VARCHAR2(10),
    Registration_Date DATE
);

-- Insert Sample Data
INSERT INTO Customer
(First_Name, Last_Name, Gender, Email, Phone, Password, Address, City, State, Pincode, Registration_Date)
VALUES
('Ananya','Sharma','Female','ananya@gmail.com','9876543210','Ananya123','12 MG Road','Bangalore','Karnataka','560001',DATE '2026-08-01');

INSERT INTO Customer
(First_Name, Last_Name, Gender, Email, Phone, Password, Address, City, State, Pincode, Registration_Date)
VALUES
('Rahul','Verma','Male','rahul@gmail.com','9876543211','Rahul123','45 Anna Nagar','Chennai','Tamil Nadu','600040',DATE '2026-08-02');

INSERT INTO Customer
(First_Name, Last_Name, Gender, Email, Phone, Password, Address, City, State, Pincode, Registration_Date)
VALUES
('Priya','Nair','Female','priya@gmail.com','9876543212','Priya123','22 Marine Drive','Kochi','Kerala','682001',DATE '2026-08-03');

INSERT INTO Customer
(First_Name, Last_Name, Gender, Email, Phone, Password, Address, City, State, Pincode, Registration_Date)
VALUES
('Arjun','Patel','Male','arjun@gmail.com','9876543213','Arjun123','78 CG Road','Ahmedabad','Gujarat','380009',DATE '2026-08-03');

INSERT INTO Customer
(First_Name, Last_Name, Gender, Email, Phone, Password, Address, City, State, Pincode, Registration_Date)
VALUES
('Sneha','Reddy','Female','sneha@gmail.com','9876543214','Sneha123','15 Jubilee Hills','Hyderabad','Telangana','500033',DATE '2026-08-03');

-- Display Records
SELECT * FROM Customer;