CREATE TABLE RATING (
    RATING_ID NUMBER PRIMARY KEY,
    PRODUCT_ID NUMBER,
    CUSTOMER_ID NUMBER,
    RATING NUMBER(1),
    RATING_DATE DATE,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
    CHECK (RATING BETWEEN 1 AND 5)
);

INSERT INTO RATING VALUES
(1, 101, 101, 5, TO_DATE('01-10-2026','DD-MM-YYYY'));

INSERT INTO RATING VALUES
(2, 102, 102, 4, TO_DATE('02-10-2026','DD-MM-YYYY'));

INSERT INTO RATING VALUES
(3, 103, 103, 5, TO_DATE('02-10-2026','DD-MM-YYYY'));

INSERT INTO RATING VALUES
(4, 104, 104, 4, TO_DATE('03-10-2026','DD-MM-YYYY'));

INSERT INTO RATING VALUES
(5, 105, 105, 5, TO_DATE('03-10-2026','DD-MM-YYYY'));

COMMIT;

SELECT * FROM RATING;

SELECT
    PRODUCT_ID,
    AVG(RATING) AS AVERAGE_RATING
FROM RATING
GROUP BY PRODUCT_ID
ORDER BY PRODUCT_ID;

SELECT
    PRODUCT_ID,
    AVG(RATING) AS AVERAGE_RATING
FROM RATING
GROUP BY PRODUCT_ID
HAVING AVG(RATING) >= 4
ORDER BY AVERAGE_RATING DESC;

SELECT
    p.PRODUCT_ID,
    p.PRODUCT_NAME,
    COUNT(r.RATING_ID) AS TOTAL_RATINGS,
    ROUND(AVG(r.RATING), 2) AS AVERAGE_RATING,
    MAX(r.RATING) AS HIGHEST_RATING,
    MIN(r.RATING) AS LOWEST_RATING
FROM RATING r
JOIN PRODUCT p
ON r.PRODUCT_ID = p.PRODUCT_ID
GROUP BY p.PRODUCT_ID, p.PRODUCT_NAME
ORDER BY AVERAGE_RATING DESC;