CREATE TABLE RATING (
    RATING_ID NUMBER PRIMARY KEY,
    PRODUCT_ID NUMBER,
    CUSTOMER_ID NUMBER,
    RATING NUMBER(1),
    RATING_DATE DATE,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
    CHECK (RATING BETWEEN 1 AND 5)
);