CREATE TABLE REVIEW (
    REVIEW_ID NUMBER PRIMARY KEY,
    PRODUCT_ID NUMBER,
    CUSTOMER_ID NUMBER,
    REVIEW_TEXT VARCHAR2(500),
    REVIEW_DATE DATE,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);

INSERT INTO REVIEW VALUES
(1, 101, 101, 'Long lasting matte lipstick', TO_DATE('01-10-2026','DD-MM-YYYY'));

INSERT INTO REVIEW VALUES
(2, 102, 102, 'Foundation gives good coverage', TO_DATE('02-10-2026','DD-MM-YYYY'));

INSERT INTO REVIEW VALUES
(3, 103, 103, 'Serum gives a nice glow', TO_DATE('02-10-2026','DD-MM-YYYY'));

INSERT INTO REVIEW VALUES
(4, 104, 104, 'Very good moisturizer', TO_DATE('03-10-2026','DD-MM-YYYY'));

INSERT INTO REVIEW VALUES
(5, 105, 105, 'Lovely fragrance', TO_DATE('04-10-2026','DD-MM-YYYY'));

COMMIT;

SELECT * FROM REVIEW;

SELECT
    r.REVIEW_ID,
    r.PRODUCT_ID,
    p.PRODUCT_NAME,
    r.CUSTOMER_ID,
    r.REVIEW_TEXT,
    r.REVIEW_DATE
FROM REVIEW r
JOIN PRODUCT p
ON r.PRODUCT_ID = p.PRODUCT_ID
ORDER BY r.REVIEW_ID;