CREATE TABLE REVIEW (
    REVIEW_ID NUMBER PRIMARY KEY,
    PRODUCT_ID NUMBER,
    CUSTOMER_ID NUMBER,
    REVIEW_TEXT VARCHAR2(500),
    REVIEW_DATE DATE DEFAULT SYSDATE,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);

CREATE TABLE RATING (
    RATING_ID NUMBER PRIMARY KEY,
    REVIEW_ID NUMBER REFERENCES REVIEW(REVIEW_ID),
    RATING_VALUE NUMBER(1) CHECK (RATING_VALUE BETWEEN 1 AND 5)
);